autobrr/autobrr.com

docs/getting-started/installation.md
Changed `syslog.target network.target` to `syslog.target network-online.target`
Reported by tijuco.
=> fix for autobrr.service

docusaurus.config.js
The blog sample is currently active and visible on https://autobrr.com/blog
This deactivates it without deleting the blog folder, and throws a "Page Not Found" if someone were to stumble upon it.
=> Deactivated blog pages

docs/configuration/download-clients.md
Fixed 2 typos in the rTorrent / ruTorrent section where Deluge was stated as download client instead of rTorrent / ruTorrent.
Changed wording to ruTorrent where only rTorrent was stated since you are technically accessing ruTorrent.
=> docs: fix deluge rTorrent / ruTorrent typos in download-clients.md

docs/faqs.md, docs/filters/actions.md
- Added rTorrent to `actions.md`
- Added warning about Deluge labels in `actions.md` - needs to exist for autobrr to use them
- Update FAQ: Deluge running in Docker (might have to enable `Allow Remote Connections` on some setups)
=> docs: added rTorrent to actions.md and updated FAQ

snippets/categories/aither.mdx, snippets/categories/pixelhd.mdx, snippets/categories/ptn.mdx, snippets/category-snippets.mdx, snippets/indexers.mdx
New supported indexers:
- Aither
- Piratethenet
- PixelHD
- BitSexy
- Cathode-Ray Tube
- DocsPedia.world
- SkipTheCommericals
Added categories from Aither, PTN and PixelHD.
=> docs: added more categories and supported indexers

docs/filters/categories.md
This PR corrects the terminology for the type of filtering used by categories.
=> docs: fix filtering terminology

docs/configuration/download-clients.md, snippets/downloadclients.mdx, snippets/shared-download-clients/deluge.mdx, snippets/shared-download-clients/lidarr.mdx, snippets/shared-download-clients/qbittorrent.mdx, snippets/shared-download-clients/radarr.mdx, snippets/shared-download-clients/readarr.mdx, snippets/shared-download-clients/rtorrent.mdx, snippets/shared-download-clients/sonarr.mdx, snippets/shared-download-clients/transmission.mdx
Created the skeleton for download client sections for shared seedboxes.
Only ultra and some seedhost and feral got added so far - will do others as soon as I gathered the data.
Feel free to contribute to this PR or ping me on discord if you have data i can add.
~~- [ ] Feral Readarr~~ Not supported
~~- [ ] hostingby.design Readarr~~ Not supported
~~- [ ] hostingby.design Transmission~~ Not supported
=> docs: add sections in download clients for shared seedboxes

snippets/shared-download-clients/deluge.mdx, snippets/shared-download-clients/lidarr.mdx, snippets/shared-download-clients/radarr.mdx, snippets/shared-download-clients/readarr.mdx, snippets/shared-download-clients/rtorrent.mdx, snippets/shared-download-clients/sonarr.mdx
Ref https://github.com/autobrr/autobrr.com/issues/68
- Deluge
- Lidarr
- Radarr
- Readarr
- rTorrent
- Sonarr
qBittorrent was impossible to get working.
Transmission not supported.
=> docs: add download clients for Bytesized Hosting

docusaurus.config.js
twitter:card made link preview images very small.
=> docs(fix): removed twitter card line from config

docs/3rd-party-tools.md
Replaced Discord with Notifiarr/Apprise for cross-seed webhook notifications as per the cross-seed docs.
=> Update 3rd-party-tools / cross-seed guide

snippets/shared-download-clients/deluge.mdx
Removed this part as its not needed for autobrr to connect to it remotely. Tested and confirmed with torrents added successfully.
Just to clarify; it worked with binding to 0.0.0.0 as well, so this is not a fix per se.
https://github.com/autobrr/autobrr.com/blob/a00e941245ff5621b3932d2cbeeb6669e8449b06/snippets/shared-download-clients/deluge.mdx?plain=1#L39-L44
=> docs: binding HBD deluge to 0.0.0.0 is not neccessary

docs/filters/basics.md, docs/filters/examples.md, docs/filters/freeleech.md, sidebars.js
I'm not quite sure if creating a dedicated page for this, is the way to go.
If someone has a better idea feel free to suggest a more suitable way!
=> add documentation on which indexers support freeleech filtering

docs/filters/actions.md
Should be merged when https://github.com/autobrr/autobrr/pull/819 is merged.
=> docs: add TorrentID and GroupID to supported macros

docs/filters/examples.md
Probably originally caused by a cut/paste of the section above it.
=> Correct typo.md

docs/configuration/download-clients/shared.md, snippets/shared-download-clients/deluge.mdx, snippets/shared-download-clients/lidarr.mdx, snippets/shared-download-clients/qbittorrent.mdx, snippets/shared-download-clients/radarr.mdx, snippets/shared-download-clients/readarr.mdx, snippets/shared-download-clients/rtorrent.mdx, snippets/shared-download-clients/sonarr.mdx, snippets/shared-download-clients/transmission.mdx
Changes:
- Add RapidSeedbox qBit, rTorrent, Transmission clients under Shared seedbox providers section
- Sort the shared seedbox providers alphabetically
=> docs: Add RapidSeedbox's Lean client configs and sort hosts by alphabet

docs/filters/categories.md
For some unapparent reason to me the xSpeeds categories won't show if it start with a lower case `x`...
=> fix(docs): xspeeds categories

snippets/shared-download-clients/qbittorrent.mdx
The URL generated for a particular user must be used in order for this to work (tested in v1.31)
=> Updates shared seedhost documentation for qbittorrent

docs/3rd-party-tools.md, src/css/custom.css, src/theme/Details/styles.module.css
This PR updates the cross-seed setup tutorial on the docs.
Please thoroughly review the iptables section and the filter creation part
and feel free to make any changes.
I don't have any strong feeling about the changes I did.
EDIT:
The tutorial uses the apikey query param instead of the X-Api-Key HTTP header..
If there is a reason why it's better to use the header feel free to elaborate!
=> chore(docs): update cross-seed tutorial

docs/filters/basics.md
I believe this is how it works after reading 
https://github.com/autobrr/autobrr/blob/develop/internal/database/filter.go#L1424-L1472
I had originally guessed that the count was over a rolling "download period" sized lookback window, thought other people might also have been confused.
=> more explanation for "max per"

docs/filters/freeleech.md
Update the documentation according to https://github.com/autobrr/autobrr/pull/1302.
=> docs: add ANT to the list of indexers supporting freeleech

snippets/seedbox-solution-installers.mdx
Autobrr is a saltbox app now instead of sandbox app so docs updated accordingly https://github.com/autobrr/autobrr/pull/1410
=> docs(installers): update Saltbox instructions

docs/filters/omegabrr.md
Some build changes for omegabrr changed the architecture name for the artifacts.
This PR fixes the download URL in the docs to match the new architecture name.
=> fix(docs): update omegabrr download URL

docs/3rd-party-tools.md
Update payload to use the new macro `IndexerName` for improved compatibility.
=> docs: update cross-seed payload to use IndexerName

docs/configuration/indexers.md
Add keywords to seed limits to easier to search for.
=> docs(indexers): add keywords to external identifier

docs/3rd-party-tools/cross-seed.md, docs/3rd-party-tools/redacted-hook.md, docs/3rd-party-tools/upgraderr.md
The markdown document is using the title from the front matter section as header, so no need for another.
=> docs: remove duplicate headers

docs/3rd-party-tools/cross-seed.md
This updates the json payload for the cross-seed filter to properly escape `"` and `'`.
Fixes https://github.com/autobrr/autobrr/issues/1802
=> fix(cross-seed): json payload

docs/configuration/indexers.md
Clarify usage of feeds to add unsupported indexers.
=> docs: clarify missing indexers support

docs/installation/supplementary/postgresql.md
Adds a notice to inform that the SQLite to PostgreSQL conversion feature is currently non-functional.
=> docs: warn about broken sqlite to postgres conversion

docs/filters/freeleech.md
`/docs/filters/freeleech.md` now use the `/snippets/freeleech.mdx` snippet and will always show the supported indexers based on https://github.com/autobrr/autobrr/tree/develop/internal/indexer/definitions
=> docs(filters): add dynamic freeleech table
