- docs/configuration/irc.md
> docs: update irc

- docs/getting-started/docker/reverse-proxy.md
- docs/getting-started/docker/setup.md
- docs/getting-started/installation.md
Update docs about default port change from 8989 to 7474.
> docs: update port

- docs/configuration/download-clients.md
- docs/filters/actions.md
- docs/introduction.md
> docs: add whisparr

- docs/configuration/indexers.md
- docs/getting-started/docker/setup.md
fixing minor typos in setup.md and added more indexers to summary in indexers.md
> minor fixes in docs

- docs/configuration/indexers.md
- Added custom indexer definitions.
- Replaced abbrevations with full name of supported indexers.
- Added MAM to list of supported indexers.
- Restructured and improved text in general.
> indexers.md

- docusaurus.config.js
Added #61 - #63 to enable dark mode on default
> Adding dark mode as default

- docs/getting-started/installation.md
> chore: update version in cmds

- snippets/downloadclients.mdx
Slight clarity enhancement for dummies like me.
> Download clients - clarify examples

- docs/configuration/indexers.md
- snippets/ipapproval.mdx
Add a tip about approving IP's that touch some API's.
> Ip approval

- docs/configuration/irc.md
- docs/installation/docker.md
- docs/installation/linux.md
- docs/installation/windows.md
Fixed 4 links that throws "Page not found"
> docs: fixed bad urls

- docs/filters/basics.md
Unless I am mistaken, i think the word was intended to be "variables". : )
> Update basics.md (spelling error)

- docs/configuration/download-clients.md
- docs/filters/actions.md
- docs/introduction.md
- snippets/features.mdx
- snippets/indexers.mdx
added missing indexers and readarr support
> readarr and indexers

- snippets/categories/animebytes.mdx
- snippets/categories/ar.mdx
- snippets/categories/fl.mdx
- snippets/categories/immortalseed.mdx
- snippets/categories/revolutiontt.mdx
- snippets/categories/tl.mdx
- snippets/categories/torrentseeds.mdx
I feel like there are still some categories missing for ImmortalSeed but I don't have them so I will just add these for now...
I could be wrong though...
> enhancement(categories): add some missing categories

- docs/configuration/autobrr.md
- docs/configuration/feeds.md
- docs/configuration/indexers.md
- docs/filters/actions.md
- docs/filters/examples.md
- docs/installation/docker.md
- docs/installation/linux.md
- docs/usage/search.md
- sidebars.js
- documented the keyword search function https://github.com/autobrr/autobrr/pull/564
- improved setup instructions (force reader to enable IRC network)
- Reverse proxy improvements
- minor changes and improvements to text
> docs: keyword search, improved setup instructions

- docs/installation/transfer-installation.md
- sidebars.js
Please review this tutorial, check it for errors and typos and feel free to leave any suggestions on how to improve it.
> docs: transfer your installation

- docs/introduction.md
I wrote this as I worked, with the help of more knowledgeable folks on Discord, to get up and running with the use case of feeding all announcements to Servarr.  I was confused about what the larger overview of autobrr is, how it's parts are intended to work together, and I couldn't find anything like that in the docs.  So I captured the bits I was confused about as I encountered them and wrote them up in narrative form here in the hopes it might help others with similar confusions.
> docs(introduction): Add a narrative quick start

- docs/3rd-party-tools.md
- docs/usage/search.md
- sidebars.js
Created a walkthrough/guide for setting up [cross-seed](https://github.com/cross-seed/cross-seed) with autobrr.
> docs(guide): cross-seed with autobrr

- docs/faqs.md
Added explanation to the FAQs about how to change your password.
```shell
autobrrctl --config /home/username/.config/autobrr change-password <USERNAME>
```
> docs(FAQ): How to change your password with autobrrctl

- snippets/category-snippets.mdx
- snippets/indexers.mdx
ref: https://github.com/autobrr/autobrr/pull/626
> docs(indexers): remove TorrentDB

- snippets/indexers.mdx
ref https://github.com/autobrr/autobrr/pull/631
> docs(indexers): remove Oppaitime

- docs/filters/actions.md
> actions: exec ftp

- docs/installation/shared-seedbox.md
- snippets/indexers.mdx
- snippets/shared-download-clients/deluge.mdx
- snippets/shared-download-clients/lidarr.mdx
- snippets/shared-download-clients/qbittorrent.mdx
- snippets/shared-download-clients/radarr.mdx
- snippets/shared-download-clients/readarr.mdx
- snippets/shared-download-clients/rtorrent.mdx
- snippets/shared-download-clients/sonarr.mdx
- snippets/shared-download-clients/transmission.mdx
- src/css/custom.css
- src/theme/Details/index.js
- src/theme/Details/styles.module.css
Changed shared-download-clients from `<tabs>` to `<details>`
- styled `<details>` tag to better match the dark theme
- added ANT and Funfile to supported indexers
- added Seedit4me to shared-download-clients
> docs: changed shared-download-clients from tabs to details

- docusaurus.config.js
- package.json
Added a search bar since the docs are starting to grow.
This is an offline / local search implementation.
Using this: https://github.com/easyops-cn/docusaurus-search-local
> feat(docs): add search bar

- docs/installation/docker.md
- docs/installation/linux.md
Added Caddy subdomain example. (Thanks cantstopwontstop!)
Added both Caddy examples to the docker page as well.
> docs: added caddy examples

- docs/configuration/download-clients/dedi.md
- docs/configuration/download-clients/shared.md
add caution note for escaping characters in ruTorrent URLs
> add caution note for escaping characters in ruTorrent URLs

- docs/configuration/autobrr.md
- docs/configuration/download-clients/dedi.md
- docs/configuration/feeds.md
- docs/configuration/indexers.md
- docs/introduction.md
- snippets/features.mdx
- snippets/indexers.mdx
- src/pages/index.js
- src/pages/index.module.css
- Added PTFiles to list of indexers
- Added Newznab to the appropriate places
- Add connection instructions for sabnzbd
- Info about magnet links
> docs: added info about changes in 1.19

- docs/configuration/feeds.md
With the following pull request merged https://github.com/autobrr/autobrr/pull/730 the information in the info box is wrong.
> Remove info box regarding support for magnet links

- src/css/custom.css
- src/pages/index.js
This will make it respond better to more narrow screens.
> fix(web): improve responsiveness and align hero-grid items consistently

- docs/3rd-party-tools.md
- docs/filters/omegabrr.md
- Added info about omegabrr lists
- Some refactoring
> docs: omegabrr update

- docs/filters/freeleech.md
Ref https://github.com/autobrr/autobrr/pull/833
> docs: update freeleech.md

- docs/faqs.md
Update FAQ about automating the use of freeleech tokens from RED
> faq: red freeleech tokens

- docs/faqs.md
This PR adds a paragragh for the TL wiki article on how to set up autobrr.
> add TL autobrr wiki article to faqs.md

- docs/faqs.md
If anyone has a one liner for CLI that’d be great
> fix(faq): add info about changing the username

- docs/filters/actions.md
- docs/filters/external.md
- docs/filters/macros.md
- docs/installation/linux.md
- sidebars.js
- src/css/custom.css
add other sprig examples to macros page
keep old /filters/actions#macros placeholder and indicate macros page url remove pagination_previous when not needed
capitalize Windows where needed
add different color for quotes
> make macros a separate page

- docs/configuration/feeds.md
- docs/filters/actions.md
- docs/usage/tips.md
- docusaurus.config.js
- src/css/custom.css
Some minor changes to placement and some css improvements.
Disabling the dropdown until at least one other version is created.
> Cosmetic changes for versioning

- docs/configuration/autobrr.md
- docs/configuration/download-clients/dedi.md
- docs/configuration/download-clients/shared.md
- docs/filters/actions.md
- docs/introduction.md
- docs/quick-start.md
- docusaurus.config.js
Fixes https://github.com/autobrr/autobrr/issues/1252
> docs: Revert URL changes

- docs/api.md
Solved in https://github.com/autobrr/autobrr/pull/1214
> docs: remove warning about enable or disable indexer

- docs/usage/tips.md
Please just check my spelling/grammar or give any input and suggestions for changes.
> Add mdblist instructions

- docs/installation/reverse-proxy/lighttpd.md
- sidebars.js
lighttpd reverse proxy example
confirmed by user that it works in https://dietpi.com/forum/t/autobrr-reverse-proxy-on-lighttpd/18626
> lighttpd reverse proxy example

- docs/installation/windows.md
> fix(installation): windows add local http url

- docs/configuration/notifications.md
Add ntfy and list available services for Shoutrrr.
> docs(notifications): add ntfy and update shoutrrr

- docs/installation/macos.md
- sidebars.js
Relies on https://github.com/Homebrew/homebrew-core/pull/161897
> docs(install): add macOS instructions

- docs/filters/basics.md
- docs/filters/music.md
- docs/filters/tv-movies.md
- docs/installation/reverse-proxy/caddy.md
- docs/installation/reverse-proxy/swag.md
- docs/installation/supplementary/transfer-installation.md
- snippets/convert-autodl-filter.mdx
- src/css/custom.css
- fix code duplication of ConvertAutodlFilter info boxes
- add macOS to transfer-installation.md
- fix indentation in in swag reverse proxy config
- caddy subfolder info concretized
- fix text color for alert boxes and collapsible sections in white theme
- minuscule CSS changes
> docs: miscellanous changes, fixes and optimizations

- sidebars.js
- snippets/seedbox-installers.mdx
This PR updates the installation and update instructions for shared seedboxes.
> update seedbox instructions

- blog/2024-02-27-v1.39.0/index.md
> docs(changelog): add v1.39.0

- blog/2024-02-28-v1.39.1/index.md
> docs(changelog): add v1.39.1

- docs/configuration/download-clients/dedi.md
- snippets/shared-download-clients/rtorrent.mdx
Add swizzin specific rtorrent setup.
> docs(download-clients): add rtorrent swizzin setup

- blog/2024-03-25-v1.40.0/index.md
- blog/2024-03-26-v1.40.1/index.md
- blog/2024-04-16-v1.41.0/index.md
- docusaurus.config.js
> chore(docs): add missing release notes

- src/css/custom.css
This was done previously, but got overridden somewhere.
> fix(release-notes): hide author

- .npmrc
- netlify.toml
- package.json
> build: set pnpm version

- docs/introduction.md
- snippets/indexers.mdx
- src/pages/index.js
Update list of supported indexers.
> docs:update supported indexers

- docs/3rd-party-tools/cross-seed.md
- docs/3rd-party-tools/manage-torrents.md
- docs/3rd-party-tools/redacted-hook.md
- docs/3rd-party-tools/upgraderr.md
- sidebars.js
Redo 3rd party tools page into category and split each tool into it's own page.
Add docs about useful tools to manage torrents.
> docs: tools to manage torrents

- docs/configuration/irc.md
> docs(irc): add disclaimer about use of bouncers

- docs/filters/freeleech.md
- snippets/indexers.mdx
> docs: remove STC and STT indexes

- snippets/freeleech.mdx
- snippets/indexers.mdx
Automated update of the indexers and freeleech support lists from definitions
> docs: update indexers and freeleech support lists

- docs/filters/basics.md
re: https://github.com/autobrr/autobrr/pull/1837
> docs(filters): add announce type

- docs/configuration/authentication.md
- docs/configuration/autobrr.md
- docs/installation/docker.md
Can be merged after https://github.com/autobrr/autobrr/pull/1908
> docs: update OIDC config to use camelCase

- docs/installation/reverse-proxy/lighttpd.md
*
* Important information for SSEWriter type of response when you are behind lighttpd
*
*
*
*
*
*
*
> Added info to reverse-proxy/lighttpd

- docs/filters/basics.md
- docs/filters/skip-duplicates.md
- sidebars.js
Try to explain what Skip Duplicates is for, how it works, and why sometimes it doesn't.
> docs: add skip duplicates

- snippets/seedbox-installers.mdx
- snippets/shared-download-clients/deluge.mdx
- snippets/shared-download-clients/qbittorrent.mdx
- snippets/shared-download-clients/radarr.mdx
- snippets/shared-download-clients/rtorrent.mdx
- snippets/shared-download-clients/sonarr.mdx
- snippets/shared-download-clients/transmission.mdx
remove manual installation script, add one-click installer blurb, add note about their custom Expert mode, add client connection information for their supported apps
> docs(installers): update instructions for Whatbox.ca 
